name: CI/CD Aplikasi PAUD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Aplikasi (Vite)
        run: npm run build
        
      - name: Deploy ke GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          
      - name: Simpan Hasil Build sebagai Artifact (Modul 5)
        uses: actions/upload-artifact@v4
        with:
          name: aplikasi-paud-siap-pakai
          path: ./dist
